
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: resume
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgresql+psycopg2://resume:resume@db:5432/resume_db
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  pgdata:
